# Seed for Initialization of parameter
seed: 42
# The Model Configuration
model:
    input_size: 29
    hidden1_size: 16
    bottleneck_size: 8
    hidden2_size: 16
    output_size: 29
# The Training Configuration
training:
    shuffle_seed: 101
    epochs: 2000
    batch_size: 256
    schedulers:
        warmup_steps: 500
        decay_steps: 2000
        init_value: 1e-6
        peak_value: 1e-2
        end_value: 1e-3
        exponent: 0.5
