# Seed for Initialization of parameter
seed: 42
# The Model Configuration
model:
    input_size: 29
    hidden1_size: 14
    bottleneck_size: 4
    hidden2_size: 14
    output_size: 29
# The Training Configuration
training:
    shuffle_seed: 101
    epochs: 500
    mini_batches: 5
    batch_size: 256
    schedulers:
        warmup_steps: 1000
        decay_steps: 5000
        init_value: 1e-6
        peak_value: 1e-2
        end_value: 1e-3
        exponent: 0.5
